# Generated by Django 5.0.1 on 2024-01-12 09:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseStudy', '0002_topic_room_host_meassage_room_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meassage',
            new_name='Message',
        ),
    ]
